version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: lunaris-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Xhf$^y8xria9
      MYSQL_DATABASE: lunaris-project
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
